### ISSUE TITLE
RSS feed icon doesn't show up?

### ISSUE THREAD

**Issue by sutibun** [backdrop-contrib/on_the_web#2] opened 2015-10-26 07:43 UTC
Added a link for RSS in the settings but on the front end, no RSS icon appears although if you hover over where it should appear, you can spot the link

**Comment by jenlampton** [comment] 2016-02-05 00:22
Hm. I can't reproduce this. I see the RSS icon in my block. Can you try the latest version of the module and see if you are still having this problem?

**Comment by jenlampton** [comment] 2017-12-28 23:07
I'm going to close this issue for now, but if anyone else experiences this problem too, please reopen!

**Comment by ghost** [comment] 2019-12-22 20:32
I'm experiencing this issue, though I'm sure the reason is different now than it was 4 years ago...

When using Font Awesome, the RSS icon doesn't appear because the code is adding the `fab` class, whereas it should be adding the `fas` class (`fab` is for 'brands' (e.g. Facebook, Twitter, etc.), whereas the RSS icon is part of the 'solid' group).

Here's a PR that fixes this: https://github.com/backdrop-contrib/on_the_web/pull/32

**Closed as completed** 2021-08-27 23:50 UTC
